# Generated by Django 6.0.6 on 2026-07-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flavour_sandbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='sandbox_idea',
            new_name='idea',
        ),
    ]
