# Generated by Django 6.0.6 on 2026-07-23 20:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mead_type', models.CharField(choices=[('TRADITIONAL', 'Traditional'), ('MELOMEL', 'Melomel (Fruit)'), ('METHEGLIN', 'Metheglin (Spiced)'), ('CYSER', 'Cyser (Apple)'), ('PYMENT', 'Pyment (Grape)'), ('BRAGGOT', 'Braggot (Malt/Ale)'), ('CAPSICUMEL', 'Capsicumel (Chilli/Pepper)'), ('HYDROMEL', 'Hydromel (Session/Low-ABV)'), ('ACERGLYN', 'Acerglyn (Maple)'), ('ACCESSORIES', 'Accessories & Merch')], default='TRADITIONAL', max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), blank=True, default=list)),
                ('description', models.TextField()),
                ('abv', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('volume', models.CharField(blank=True, choices=[('500ML', '500ml'), ('1L', '1L'), ('4L', '4L')], max_length=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('stock_level', models.PositiveIntegerField(default=0)),
                ('clearance', models.BooleanField(default=False)),
                ('most_popular', models.BooleanField(default=False)),
                ('mead_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
        ),
    ]
