# Generated by Django 6.0.6 on 2026-07-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='mead_type',
            field=models.CharField(choices=[('TRADITIONAL', 'Traditional'), ('MELOMEL', 'Melomel (Fruit)'), ('METHEGLIN', 'Metheglin (Spiced)'), ('CYSER', 'Cyser (Apple)'), ('PYMENT', 'Pyment (Grape)'), ('BRAGGOT', 'Braggot (Malt/Ale)'), ('CAPSICUMEL', 'Capsicumel (Chilli/Pepper)'), ('HYDROMEL', 'Hydromel (Session/Low-ABV)'), ('ACERGLYN', 'Acerglyn (Maple)'), ('ACCESSORIES', 'Accessories & Merch')], default='TRADITIONAL', max_length=20, unique=True),
        ),
    ]
