# Generated by Django 6.0.6 on 2026-08-03 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Stock level in liters', max_digits=10),
        ),
    ]
